// https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#polyfill
Function.prototype.bind||(Function.prototype.bind=function(c){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var d=Array.prototype.slice.call(arguments,1),e=this,a=function(){},b=function(){return e.apply(this instanceof a?this:c,d.concat(Array.prototype.slice.call(arguments)))};this.prototype&&(a.prototype=this.prototype);b.prototype=new a;return b});

// https://github.com/douglascrockford/JSON-js/blob/master/json2.js
"object"!==typeof JSON&&(JSON={});
(function(){function n(b){return 10>b?"0"+b:b}function r(){return this.valueOf()}function t(b){u.lastIndex=0;return u.test(b)?'"'+b.replace(u,function(e){var c=w[e];return"string"===typeof c?c:"\\u"+("0000"+e.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function p(b,e){var c,h=f,a=e[b];a&&"object"===typeof a&&"function"===typeof a.toJSON&&(a=a.toJSON(b));"function"===typeof m&&(a=m.call(e,b,a));switch(typeof a){case "string":return t(a);case "number":return isFinite(a)?String(a):"null";case "boolean":case "null":return String(a);
case "object":if(!a)return"null";f+=q;var g=[];if("[object Array]"===Object.prototype.toString.apply(a)){var k=a.length;for(c=0;c<k;c+=1)g[c]=p(c,a)||"null";var d=0===g.length?"[]":f?"[\n"+f+g.join(",\n"+f)+"\n"+h+"]":"["+g.join(",")+"]";f=h;return d}if(m&&"object"===typeof m)for(k=m.length,c=0;c<k;c+=1){if("string"===typeof m[c]){var l=m[c];(d=p(l,a))&&g.push(t(l)+(f?": ":":")+d)}}else for(l in a)Object.prototype.hasOwnProperty.call(a,l)&&(d=p(l,a))&&g.push(t(l)+(f?": ":":")+d);d=0===g.length?"{}":
f?"{\n"+f+g.join(",\n"+f)+"\n"+h+"}":"{"+g.join(",")+"}";f=h;return d}}var x=/^[\],:{}\s]*$/,y=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,z=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,A=/(?:^|:|,)(?:\s*\[)+/g,u=/[\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,v=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;"function"!==typeof Date.prototype.toJSON&&
(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+n(this.getUTCMonth()+1)+"-"+n(this.getUTCDate())+"T"+n(this.getUTCHours())+":"+n(this.getUTCMinutes())+":"+n(this.getUTCSeconds())+"Z":null},Boolean.prototype.toJSON=r,Number.prototype.toJSON=r,String.prototype.toJSON=r);var f,q,m;if("function"!==typeof JSON.stringify){var w={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};JSON.stringify=function(b,e,c){var h;q=f="";if("number"===
typeof c)for(h=0;h<c;h+=1)q+=" ";else"string"===typeof c&&(q=c);if((m=e)&&"function"!==typeof e&&("object"!==typeof e||"number"!==typeof e.length))throw Error("JSON.stringify");return p("",{"":b})}}"function"!==typeof JSON.parse&&(JSON.parse=function(b,e){function c(a,g){var k,d=a[g];if(d&&"object"===typeof d)for(k in d)if(Object.prototype.hasOwnProperty.call(d,k)){var l=c(d,k);void 0!==l?d[k]=l:delete d[k]}return e.call(a,g,d)}b=String(b);v.lastIndex=0;v.test(b)&&(b=b.replace(v,function(a){return"\\u"+
("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(x.test(b.replace(y,"@").replace(z,"]").replace(A,""))){var h=eval("("+b+")");return"function"===typeof e?c({"":h},""):h}throw new SyntaxError("JSON.parse");})})();